// demo/react/src/components/SideMenu/SideMenu.js
import React, {useState} from 'react';

function SideMenu(props) {
    const [collapse, setCollapse] = useState(false)
    const [dropdownOpened, setDropdownOpened] = useState(false)

    const clickCollapse = () => {
        setCollapse(!collapse)
    }
    const dropdownClick = (e) => {
        setDropdownOpened(!dropdownOpened)
    }
    // function clickCollapse(){
    //     document.querySelector(".sdds-sidebar").classList.toggle('sdds-sidebar-collapse');
    //     return false;
    // }
    //
    // const popover = document.querySelector('#popover');
    // popover.addEventListener("mouseleave", hidePopover, false);
    //
    // const sidebar = document.querySelector('.sdds-sidebar');
    //
    // const menus = document.querySelectorAll('.sdds-navbar-menu-hover');
    // menus.forEach(function(menu){
    //     menu.addEventListener("mouseenter", onHoverMenu, false);
    //     menu.addEventListener("mouseleave", onLeaveMenu, false);
    // });
    //
    // function onLeaveMenu(event){
    //     // hide popover if mouse position outside of popover.getBoundingClientRect()
    // }
    //
    // function hidePopover(event){
    //     if(!sidebar.classList.contains('sdds-sidebar-collapse')) return;
    //
    //     popover.style.display = 'none';
    //     popover.innerHTML='';
    // }
    //
    // function onHoverMenu(event){
    //     if(!sidebar.classList.contains('sdds-sidebar-collapse')) return;
    //
    //     popover.innerHTML='';
    //
    //     var elem = event.target;
    //     var posX = elem.getBoundingClientRect().left + elem.offsetWidth + 2;
    //     var posY = elem.getBoundingClientRect().top;
    //     var classes = event.target.className;
    //     var newElem = document.createElement('div');
    //
    //     newElem.className = classes;
    //     newElem.innerHTML = elem.innerHTML;
    //
    //     popover.appendChild(newElem);
    //     popover.style.top = posY + 'px';
    //     popover.style.left = posX + 'px';
    //     popover.style.display = 'block';
    //
    // function dropdownClick(event){
    //     // console.log(event)
    //     event.classList.toggle('opened');
    // }


    return (

        <div className="sdds-push sdds-demo-container">
            <div className={`sdds-sidebar expanded ${collapse ? 'sdds-sidebar-collapse' : null}`}>
                <div className="sdds-navbar-side-menu expanded"
                     // style={{position: 'relative'}}
                >
                    <ul className="sdds-navbar-menu-list">
                        <li className={"sdds-navbar-menu-item sdds-navbar-menu-hover"}>
                            {
                                collapse &&
                                    <div id="popover"
                                         className="sdds-navbar-menu-popover"
                                         style={{position: 'fixed'}}>

                                    </div>
                            }
                            <span className="sdds-navbar-icon-button">
                                <svg width="20" height="20" viewBox="0 0 20 20"
                                     fill="#e2e2e4"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <rect y="0.334473" width="20" height="20"/> </svg></span>
                            <a className="sdds-navbar-menu-item-link" href="#">
                                Item 1
                            </a>
                        </li>
                        <li className="sdds-navbar-menu-item sdds-navbar-menu-hover">
                            <span className="sdds-navbar-icon-button">
                                <svg width="20" height="20" viewBox="0 0 20 20"
                                     fill="#e2e2e4"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <rect y="0.334473" width="20" height="20"/> </svg></span>
                            <a className="sdds-navbar-menu-item-link" href="#">
                                Item 2
                            </a>
                        </li>

                        <li className="sdds-navbar-menu-item sdds-navbar-menu-hover">
                            <span className="sdds-navbar-icon-button"><svg width="20" height="20" viewBox="0 0 20 20"
                                                                           fill="#e2e2e4"
                                                                           xmlns="http://www.w3.org/2000/svg"><rect
                                y="0.334473" width="20" height="20"/> </svg></span>
                            <a className="sdds-navbar-menu-item-link" href="#">
                                Item 3
                            </a>
                        </li>
                        <li className="sdds-navbar-menu-item sdds-navbar-menu-hover">
                            <span className="sdds-navbar-icon-button"><svg width="20" height="20" viewBox="0 0 20 20"
                                                                           fill="#e2e2e4"
                                                                           xmlns="http://www.w3.org/2000/svg"><rect
                                y="0.334473" width="20" height="20"/> </svg></span>
                            <a className="sdds-navbar-menu-item-link" href="#">
                                Item 4
                            </a>
                        </li>
                        <li className={`sdds-navbar-menu-item-dropdown sdds-navbar-menu-hover ${dropdownOpened ? "opened":null}`}
                            onClick={() => dropdownClick()}>
                            <div className="sdds-navbar-menu-item-dropdown-parent">
                                <span className="sdds-navbar-icon-button">
                                    <svg width="20" height="20"
                                         viewBox="0 0 20 20" fill="#e2e2e4"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <rect y="0.334473" width="20" height="20"/> </svg></span>
                                <a className="sdds-navbar-menu-item-link" href="#">
                                    <span className="sdds-menu-item-dropdown-text">Item 5</span>
                                    <span className="sdds-icon-arrow"/>
                                </a>
                            </div>
                            <ul className={"sdds-navbar-menu__dropdown-menu"}>
                                <li className="sdds-navbar-menu__dropdown-item"><a href="#">Sub item 3-1 long
                                    label...</a></li>
                                <li className="sdds-navbar-menu__dropdown-item active"><a href="#">Sub item 3-2</a></li>
                                <li className="sdds-navbar-menu__dropdown-item"><a href="#">Sub item 3-3</a></li>
                                <li className="sdds-navbar-menu__dropdown-item"><a href="#">Sub item 3-4</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div className="sdds-navbar-menu-item sdds-navbar-menu-item-bottom sdds-navbar-menu-hide-on-mobile"
                         onClick={() => clickCollapse()}
                    >
                        <span className="sdds-navbar-icon-button">
                            <svg width="20" height="20" viewBox="0 0 20 20"
                                 fill="#e2e2e4"
                                 xmlns="http://www.w3.org/2000/svg">
                                <rect y="0.334473" width="20" height="20"/> </svg></span>
                        <a id="collapse-btn" className="sdds-navbar-menu-item-link" href="#">
                            Collapse
                        </a>
                    </div>
                </div>
                <div id="popover"
                     className="sdds-navbar-menu-popover"
                     style={{display: 'none', position: 'fixed'}}>

                </div>
            </div>
        </div>
    );
}

export default SideMenu;

// demo/angular/angular11/src/app/components/side-menu/side-menu.component.ts
import { Component, ElementRef, EventEmitter, Input, OnInit, Output } from '@angular/core';


@Component({
  selector: 'app-side-menu',
  templateUrl: './side-menu.component.html',
  styleUrls: ['./side-menu.component.scss'],
  host: {
    '(document:click)': 'reset($event)',
  },
})
export class SideMenuComponent implements OnInit {
  selectedMenu = 'other/form';
  dropDownExpanded = false;
  dropDownActive = false;
  collapse = false;
  @Input() isExpanded: boolean;
  constructor(private _eref: ElementRef) { }

  ngOnInit(): void {}

  ngAfterViewInit() {
    const menus = document.querySelectorAll('.sdds-navbar-menu-hover');
    menus.forEach((menu) => {
      menu.addEventListener('mouseenter', this.onHoverMenu, false);
    });
  }

  changeMenu(value: MouseEvent): void {
    const menu = (value.target as HTMLInputElement).querySelector('a')?.innerHTML.toLowerCase()
      ? (value.target as HTMLInputElement).querySelector('a')?.innerHTML.toLowerCase()
      : (value.target as HTMLInputElement).innerHTML.toLowerCase();
    this.selectedMenu = 'other/' + menu;
    (value.target as HTMLInputElement)?.closest('.sdds-navbar-menu-item-dropdown')?.classList.remove('opened');
    this.dropDownActive = true;
    this.dropDownExpanded = false;
    this.collapse = false;
  }

  onHoverMenu(event) {
    console.log('if it is collapsed show popover', 'x:', event.screenX, 'y:', event.screenY);
  }

  dropdownClick(event) {
    if (document.querySelector('.sdds-sidebar')?.classList.contains('sdds-sidebar-collapse')) {
      this.collapse = true;
      this._eref.nativeElement.querySelector('.sdds-sidebar').classList.toggle('sdds-sidebar-collapse');
      event?.closest('.sdds-navbar-menu-item-dropdown')?.classList.add('opened');
      this.dropDownActive = false;
      this.dropDownExpanded = true;
    }
    else {
      this.collapse = false;
      const dropdownParent = document.querySelector('#other');
      dropdownParent?.classList.remove('active');
      if (!this.dropDownExpanded) {
        event?.closest('.sdds-navbar-menu-item-dropdown')?.classList.add('opened');
        this.dropDownActive = false;
        this.dropDownExpanded = true;
      }
      else {
        event?.closest('.sdds-navbar-menu-item-dropdown')?.classList.remove('opened');
        const classExpanded = document.querySelectorAll('.sdds-navbar-menu__dropdown-item');
        classExpanded.forEach(element => {
          if (element.classList.contains('active')) {
            this.dropDownActive = true;
            this.dropDownExpanded = false;
          }
          else {
            this.dropDownActive = false;
            this.dropDownExpanded = false;
          }
        });
      }
    }
  }

  clickCollapse() {
    if (document.querySelector('.sdds-sidebar')?.classList.contains('sdds-sidebar-collapse')) {
      console.log('collapsed');
    }
    this._eref.nativeElement.querySelector('.sdds-sidebar').classList.toggle('sdds-sidebar-collapse');
    return false;
  }

  reset(event) {
    const dropdownRef = this._eref.nativeElement.querySelector('.sdds-navbar-menu-item-dropdown');
    if (!event.target.closest('.sdds-navbar-menu-item-dropdown-parent') && this.collapse) {
      this.collapse = false;
    }
    if (
      !event.target.closest('.sdds-navbar-menu__dropdown-item')
      && !event.target.closest('.sdds-navbar-menu-item-bottom')
      && !this.collapse
    ) {
      this.collapse = false;
      if (this.dropDownExpanded) {
        const drop = (event.target as HTMLInputElement)?.closest('.sdds-navbar-menu-item-dropdown-parent');
        if (drop) {
          this.dropDownActive = false;
        }
        else {
          dropdownRef?.classList.remove('opened');
          this.dropDownExpanded = false;
          this.dropDownActive = false;
        }
      }
      else {
        this.dropDownActive = false;
      }
    }
  }



}

<div class="sdds-sidebar" [ngClass]="{ 'expanded': isExpanded }">
  <div class="sdds-navbar-side-menu" [ngClass]="{ 'expanded': isExpanded }">
    <ul id="menu-list" class="sdds-navbar-menu-list">

      <li class="sdds-navbar-menu-item sdds-navbar-menu-hover" routerLink="/home"
          routerLinkActive="active">
                <span class="sdds-navbar-icon-button">
                  <svg width="20" height="20" viewBox="0 0 20 20" fill="#e2e2e4"
                                                           xmlns="http://www.w3.org/2000/svg">
                        <rect y="0.334473" width="20" height="20" />
                    </svg></span>
        <a class="sdds-navbar-menu-item-link" id="home">
          Home
        </a>
      </li>

      <li id="form" routerLink="/form" class="sdds-navbar-menu-item sdds-navbar-menu-hover"
          routerLinkActive="active">
                <span class="sdds-navbar-icon-button">
                  <svg width="20" height="20" viewBox="0 0 20 20" fill="#e2e2e4"
                                                           xmlns="http://www.w3.org/2000/svg">
                        <rect y="0.334473" width="20" height="20" />
                    </svg></span>
        <a class="sdds-navbar-menu-item-link">
          Form
        </a>
      </li>

      <li id="other" class="sdds-navbar-menu-item-dropdown sdds-navbar-menu-hover"
          (click)="dropdownClick($event.target)" routerLinkActive="active">
        <div class="sdds-navbar-menu-item-dropdown-parent">
                    <span class="sdds-navbar-icon-button">
                      <svg width="20" height="20" viewBox="0 0 20 20" fill="#e2e2e4"
                                                               xmlns="http://www.w3.org/2000/svg">
                            <rect y="0.334473" width="20" height="20" />
                        </svg></span>
          <a class="sdds-navbar-menu-item-link">
            <span class="sdds-menu-item-dropdown-text">Other</span>
            <span class="sdds-icon-arrow"></span>
          </a>
        </div>

        <ul class="sdds-navbar-menu__dropdown-menu">
          <li routerLinkActive="active" class="sdds-navbar-menu__dropdown-item">
            <a routerLink="/other/form" (click)="changeMenu($event)">dropdown 1</a>
          </li>
          <li routerLinkActive="active" class="sdds-navbar-menu__dropdown-item">
            <a routerLink="/other/news" (click)="changeMenu($event)">dropdown 2</a>
          </li>
        </ul>
      </li>

    </ul>

    <div class="sdds-navbar-menu-item sdds-navbar-menu-item-bottom sdds-navbar-menu-hide-on-mobile"
         (click)="clickCollapse()">
            <span class="sdds-navbar-icon-button">
              <svg width="20" height="20" viewBox="0 0 20 20" fill="#e2e2e4"
                                                       xmlns="http://www.w3.org/2000/svg">
                    <rect y="0.334473" width="20" height="20" />
                </svg></span>
      <a id="collapse-btn" class="sdds-navbar-menu-item-link" href="#">
        Collapse
      </a>
    </div>
  </div>
</div>
