// demo/angular/angular11/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit{
  isExpanded = false;
  title = 'angular';

  ngOnInit(): void {}
}

<sdds-theme></sdds-theme>
<div class="sdds-navbar-overlay" [ngClass]=" { 'expanded' : isExpanded }"></div>
<app-header></app-header>
<div class="sdds-push">
  <app-side-menu [isExpanded]="isExpanded"></app-side-menu>
  <div class="sdds-content-push">
    <div class="sdds-container-push-fluid sdds-container">
      <app-main></app-main>
    </div>
    <app-footer></app-footer>
  </div>
</div>

// demo/react/src/App.js
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import Header from './components/header/Header';
import Form from './components/form/Form';
import Home from './components/home/Home';
import Footer from './components/footer/Footer';
import SideMenu from './components/SideMenu/SideMenu';

function App() {
  return (
    <div id="root" className="App">
      <Router>
        <sdds-theme />
        <div className="sdds-navbar-overlay expanded" />

        <Header />

        <div className="sdds-push sdds-demo-container">
          <SideMenu />

          <div className={'sdds-content-push'}>
            <div className="sdds-container-fluid content-wrapper">
              <Switch>
                <Route exact path="/">
                  <Home />
                </Route>
                <Route path="/form">
                  <Form />
                </Route>
              </Switch>
            </div>
            <Footer />
          </div>
        </div>
      </Router>
    </div>
  );
}

export default App;
