// demo/angular/angular13/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  isExpanded = false;
  title = 'angular13';
  onExpand(): void {
    this.isExpanded = !this.isExpanded;
  }
}

<sdds-theme></sdds-theme>
<div class="sdds-navbar-overlay" [ngClass]="{ expanded: isExpanded }"></div>
<app-header (expand)="onExpand()" [isExpanded]="isExpanded"></app-header>
<div class="sdds-push">
  <app-side-menu [isExpanded]="isExpanded"></app-side-menu>
  <div class="sdds-content-push">
    <div class="sdds-container-push-fluid sdds-container">
      <app-main></app-main>
    </div>
    <app-footer></app-footer>
  </div>
</div>

// sandbox/react/src/App.js
import { useState } from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import Header from './components/header/Header';
import Form from './components/form/Form';
import Home from './components/home/Home';
import Footer from './components/footer/Footer';
import SideMenu from './components/sideMenu/SideMenu';

function App() {
  const [expand, setExpand] = useState(false);
  return (
    <div id="root" className="App">
      <Router>
        <sdds-theme />
        <div className={`sdds-navbar-overlay ${expand ? 'expanded' : null}`} />
        <Header onDrawerClick={() => setExpand(!expand)} expand={expand} />
        <div className="sdds-push sdds-demo-container">
          <SideMenu expand={expand} />
          <div className={'sdds-content-push'}>
            <div className="sdds-container-fluid content-wrapper">
              <Switch>
                <Route exact path="/">
                  <Home />
                </Route>
                <Route path="/form">
                  <Form />
                </Route>
              </Switch>
            </div>
            <Footer />
          </div>
        </div>
      </Router>
    </div>
  );
}

export default App;
