// demo/react/src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import { defineCustomElements, addTheme } from '@scania/components';
import { theme as scania } from '@scania/theme-light';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

console.warn(
  'This is a demo application, please visit https://digitaldesign.scania.com for more information regarding SDDS implementation'
);

defineCustomElements();
addTheme(scania);

// demo/angular/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { addTheme, defineCustomElements } from '@scania/components';
import { theme as scania } from '@scania/theme-light';
import { style } from '@angular/animations';

if (environment.production) {
  enableProdMode();
}

console.warn(
  'This is a demo application, please visit https://digitaldesign.scania.com for more information regarding SDDS implementation'
);

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));

defineCustomElements();
addTheme(scania);
