// demo/angular/angular11/src/app/components/header/header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  @Input() isExpanded: boolean;
  @Output() expand = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}
}

<nav class="sdds-navbar">
  <button
    id="menu-mobile"
    class="sdds-navbar-icon-button sdds-navbar-side-menu-drawer"
    [ngClass]="{expanded:isExpanded}"
    (click)="expand.emit()"
  >
    <span class="sdds-icon-drawer"></span>
  </button>
  <div class="sdds-navbar-application-brand">SDDS Demo Angular</div>
  <div class="sdds-navbar-scania-brand"></div>
</nav>

// demo/react/src/components/header/Header.js
import './Header.css';

const Header = () => {
  return (
    <nav className="sdds-navbar">
      <button className="sdds-navbar-icon-button sdds-navbar-side-menu-drawer expanded">
        <span className="sdds-icon-drawer" />
      </button>
      <div className="sdds-navbar-application-brand">SDDS DEMO REACT</div>
      <div className="sdds-navbar-scania-brand" />
    </nav>
  );
};

export default Header;
